apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-service-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client-service #Find the pods with the label app: client-service 
  template:
    metadata:
      labels:
        app: client-service
    spec:
      containers:
        - name: client-service
          image: anasna/client-service:latest
---
apiVersion: v1
kind: Service
metadata:
  name: client-service
spec:
  selector:
    app: client-service
  ports:
    - name : client-service
      protocol: TCP
      port: 8080
      targetPort: 8080
